### ISSUE TITLE
fix button color for IE11

### ISSUE THREAD

**Issue by coliff** [dieulot/ip.dog#1]
(This is with IE11 on Windows 10)

![image](https://user-images.githubusercontent.com/1212885/75147392-86d74600-5740-11ea-8e50-fa6fa624f0aa.png)

**Comment by XhmikosR** [comment]
IE doesn't support CSS variables, unfortunately.

https://caniuse.com/#feat=css-variables

One would need to add fallbacks. As a side note, I'd also switch to ES5 (const -> var, since var is shorter and works with all the browsers out there)

**Comment by dieulot** [comment]
Thanks, but I’m not interested in IE support.
